### ISSUE TITLE
spelling mistakes

### ISSUE THREAD

**Issue by Yagodron** [leovdw/SubtleGuide#4]
1) Introduction - "Theorie crafter"
![error 1](https://user-images.githubusercontent.com/12407219/29819195-503e6474-8cc8-11e7-86f8-70d09bcfb457.png)
2) Equipment/Gearing Content and System - "doungeon" 2 times in there, "doungen"
![error 2](https://user-images.githubusercontent.com/12407219/29819234-74ed981c-8cc8-11e7-8af0-bc38512ba2a5.png)
![error 3](https://user-images.githubusercontent.com/12407219/29819282-ad98b228-8cc8-11e7-8d17-82900663552d.png)
3) Equipment/Tier pieces - "attribut" 2 times like on the screenshot
![error 4](https://user-images.githubusercontent.com/12407219/29819336-f523a440-8cc8-11e7-8b20-7823fa1d9021.png)
4) Equipment/Gearing up and attribut distribution - "attribut" in the paragraph name
5) Equipment/Interessting Items - "Interessting" in the paragraph name

P.S. ffs fuu, i'll send you a dictionary one day =)

**Comment by leovdw** [comment]
Thx for th feedback 
Looking at it now

**Comment by kaizerfreak** [comment]
Some more spelling/grammar feedback on DfA rotation page
https://puu.sh/xmjLL/97469abbb0.png

Also if you can put spaces after links to skills where appropriate, it would look much better.
https://puu.sh/xmjMA/95b8d47126.png

**Comment by leovdw** [comment]
Done, uploading it
