### ISSUE TITLE
Spelling/grammar issues and suggestions

### ISSUE THREAD

**Issue by banelings** [leovdw/SubtleGuide#8]
**Landing page issues** - https://leovdw.github.io/SubtleGuide/
- http://prntscr.com/gehcm4 "and" -> "an"
- http://prntscr.com/gehcwk "mas" -> "as"
- http://prntscr.com/gehdcw "coud" -> "could"
- http://prntscr.com/gehdm5 remove the space between "it" and the exclamation point "!"
- http://prntscr.com/gehe1d capitalize the "i"s
- http://prntscr.com/geheje "current" -> "currently"

**"Basics" issues** - https://leovdw.github.io/SubtleGuide/guide_basics.html
- http://prntscr.com/gehgnj "aswell" -> "as well"
- http://prntscr.com/gehgy6 "specification" -> "specialization"
- http://prntscr.com/gehhav "witch" -> "which"
- http://prntscr.com/gehhqd "capacity" -> "capability"
- http://prntscr.com/gehi4g "categorie" -> "category"
- http://prntscr.com/gehijz "Starmina" -> "Stamina"
- http://prntscr.com/gehiso "out" -> "our"
- http://prntscr.com/gehj2f "secoundary" -> "secondary"
- http://prntscr.com/gehjc1 "Juwlry" -> "Jewelry"
- http://prntscr.com/gehjkk "Starmina as main stat" -> "Stamina as a main stat"
- http://prntscr.com/gehk2p "The Idea is to wear gear that offers the more beneficial" -> "The idea...offers the most beneficial"
- http://prntscr.com/gehkn2 "dont" -> "don't"
- http://prntscr.com/gehkwf "secoundary" -> "secondary"
- http://prntscr.com/gehl3g "a item" -> "an item"
- http://prntscr.com/gehld5 "...item level offers more benefits then..." -> "item level can offer more of a benefit than a higher item level one"
- http://prntscr.com/gehm38 "tent" -> "tend"
- http://prntscr.com/gehmef "secoundary" -> "secondary"
- http://prntscr.com/gehmow "one" -> "a"
- http://prntscr.com/gehmxy "secoundary" -> "secondary"
- http://prntscr.com/gehn50 "attribut" -> "attribute"
- http://prntscr.com/gehner "prioritise" -> "prioritizes"
- http://prntscr.com/gehnsl -> "Agility > Mastery > Versatility > Critical Strike Rating > Haste Rating"
- http://prntscr.com/gehoe4 "Starmina" -> "Stamina"
- http://prntscr.com/gehopu All of the "increses/increse" to "increases"
- http://prntscr.com/gehpe1 "charakters" -> "character's"
- http://prntscr.com/gehppa "ctitical" -> "critically"
- http://prntscr.com/geiofc "decreses" -> "decreases"
- http://prntscr.com/geiopk "appearence" -> "appearance"
- http://prntscr.com/geitwj "aswellthat" -> "as well that"
- http://prntscr.com/gejanv "in form" -> "in the form"
- http://prntscr.com/gejazm "then" -> "than"
- http://prntscr.com/gejb9w "diffrence" -> "difference"
- http://prntscr.com/gejbjq "...enough this let us the choice to decide to play..." -> "enough which lets us choose to play..."
- http://prntscr.com/gejcax "Those" -> "These"
- http://prntscr.com/gejcl6 "Aliance" -> "Alliance"
- http://prntscr.com/gejcro "Is our" -> "Our"
- http://prntscr.com/gejczj "Nigth Elf (Aliance)" -> "Night Elf (Alliance)
- http://prntscr.com/gejd87 "aswell" -> "as well"
- http://prntscr.com/gejdhv "aswell as give us the..." -> "as well as gives us the..."
- http://prntscr.com/gejdxt "provides" -> "Provides"
- http://prntscr.com/geje4n "increse" -> "increase"
- http://prntscr.com/gejed0 "Professions allowes" -> "Professions allow"
- http://prntscr.com/gejeph "gear advancements" -> "gear upgrades"
- http://prntscr.com/gejeur "gimics" -> "gimmicks"
- http://prntscr.com/gejtwr "our" -> "your"
- http://prntscr.com/geju05 "Those" -> "These"
- http://prntscr.com/gejud6 "Alchemie" -> "Alchemy"
- http://prntscr.com/gejujs "Chossing this profesion allowes you to save quite alot of money for flasks."   -> "Choosing this profession allows you to save quite a lot of money on flasks."
- http://prntscr.com/gejuxy "Provides you acess to additional enchants for your back and writst those offer you for example an..." -> "Provides you access to additional enchants for your back and wrist which offer you, for example, an..."
- http://prntscr.com/gejvls "rapair" -> "repair"
- http://prntscr.com/gejw5c "beeing" -> "being"
- http://prntscr.com/gejwap "close range" -> "close-range"
- http://prntscr.com/gejwgs "majority abilities" -> "majority of our abilities"
- http://prntscr.com/gejwo1 "...range.The hitbox is an additional proporty of Enemys that..." -> "...range. The hitbox is an additional property of enemies that..."
- http://prntscr.com/gejx6t "abit" -> "a bit"
- http://prntscr.com/gejxei "Block.Creatures can not" -> "Block. Creatures cannot"
- http://prntscr.com/gejxrc "an" -> "a"
- http://prntscr.com/gejxvu "calles" -> "called"
- http://prntscr.com/gejy74 "beeing" -> "being"
- http://prntscr.com/gejyc0 "peform abilities and automated attacks." -> "perform abilities and auto attacks."
- http://prntscr.com/gejyv6 "Behind the target doesent nessecery means visualy behind.The game" -> "Behind the target doesn't necessarily mean visually behind. The game"
- http://prntscr.com/gejz6b "Save Spot" -> "Safe Area"
- http://prntscr.com/gejzdp "Ressources" x2 -> "Resources"
- http://prntscr.com/gejzml "regenerates with 10 energy/secound." -> "regenerates at a rate of 10 energy/second."
- http://prntscr.com/gejzxk "ressource" -> "resource"
- http://prntscr.com/gek06t "sutch" -> "such"
- http://prntscr.com/gek0be Put a space between the end of the Shadow Techniques link and the word "and"
- http://prntscr.com/gek0mm "secoundary" -> "secondary"
- http://prntscr.com/gek0up "sutch" -> "such"
- http://prntscr.com/gek101 "race recail" -> "racial ability"
- http://prntscr.com/gek16o "spend" -> "spent"
- http://prntscr.com/gek1jb "diffrent" x2 -> "different"
- http://prntscr.com/gek1qh "ressources, damage amplifyer" -> "resources, damage amplification"
- http://prntscr.com/gek1xq "reducrion" -> "reduction"
- http://prntscr.com/gek269 "builder" -> "builders"
- http://prntscr.com/gek2pq "main ressource and create our secoundary ressource" -> "main resource and create our secondary resource (combo points)"
- http://prntscr.com/gek357 "secoundary ressource but also require our main ressource, our damage is shifted into those(over 60% of our damage comes from finishing abilities)." -> "secondary resource but also require our main resource. The majority of our damage comes from our finishing abilities (typically over 60%)." _Just a personal suggestion on how to word that bit better_
- http://prntscr.com/gek40s "There are" -> "There is"
- http://prntscr.com/gek48f "Shadowdance" -> "Shadow Dance"
- http://prntscr.com/gek4mv "30% the" -> "30% of the"
- http://prntscr.com/gekart "every 4th swing 50% and 5th 100% (if 4th doesnt proc)" -> "every 4th swing (50% chance) or 5th swing (100% chance if the 4th swing doesn't proc)" _another personal suggestion on some slightly better wording_
- http://prntscr.com/gekbm6 "incresed" -> "increased"
- http://prntscr.com/gekbsj "Whispercp proc depens on" -> "Whisper, while the CP proc depends on"
- http://prntscr.com/gekc6b "Talents are together with legendary items the main variable that alter the gameplay." -> "Talents, together with legendaries, are the main variable that alter our gameplay."
- http://prntscr.com/gekck6 "Those depend on the fight type, lengh and used gear.Its recommendet to use a simulation to to evaluate those choices." -> "Talent selection depends on the fight type, length, and equipped gear. It is recommended to use a simulation to evaluate your choices."
- http://prntscr.com/gekd0m "tier boni benefit diffrent talent" -> "tier bonuses benefit different talent"
- http://prntscr.com/gekddb "It shold generaly seen behave like this:" -> _I'd either say delete this line completely. Having difficulty trying to reword it and it's a little unneeded_
- http://prntscr.com/gekjid "Shadowdance/Vnaish/Stealth" -> "Shadow Dance/Vanish/Stealth"
- http://prntscr.com/gekjtz "in combinations with high Shadowdance uptimes." -> "in combination with high Shadow Dance uptime."
- http://prntscr.com/gekk5p "adviced" -> "advised"
- http://prntscr.com/gekkfu _Possibly add an item link for Insignia of Ravenholdt?_
- http://prntscr.com/gekl04 "Shadowdance/Vanish/Stealth" -> "Shadow Dance/Vanish/Stealth"
- http://prntscr.com/gekl80 "secound of Shadowdance" -> "second of Shadow Dance"
- http://prntscr.com/gel5q6 "The changes made the talent in general less powerfull but it synergises weill with theShadow Satyr's Walk Legendary." -> "The changes made the talent generally less powerful. However it synergizes well with Shadow Satyr's Walk." _Possibly add item link to the legendary item_
- http://prntscr.com/gel6pi "trashold" -> "threshold"
- http://prntscr.com/gel72z "on Finisher, additional damage from the linear CP scaling if you finish at 6 CP ontop of a stronger Finality." -> "on finishing moves, additional damage from the linear CP scaling if you finish at 6 CP, as well as stronger Finality bonuses."
- http://prntscr.com/gel7fy "prevent ccombo point overcaping." -> "prevent combo point over-capping"
- http://prntscr.com/gel7v7 "its" -> "it's"
- http://prntscr.com/gel82z "Provides you a higher energy pool and slightly srtronger Energy regeneration. Its adviced to use this talent if you are new to the spec." -> "Provides you with a larger energy pool and slightly stronger energy regeneration. It's advised to use this talent if you are new to the spec."
- http://prntscr.com/gel8jc "Shifts your damage in the Dance window. We usualy want higher burst damage, this meakes this options the go-to choice." -> "Boosts your damage during Shadow Dance. We usually want higher burst damage which makes this option the go-to choice."
- http://prntscr.com/gel8u9 "seen to the other talent choices weak." -> "seen as the weakest talent choice in this row."
- http://prntscr.com/gel99t "Provides higher Shadowdance cdr and an additional charge. The Shadowdance uptime is significant higher providing higher benefits from soothing darkness. Is likely a good choice in aoe situations." -> "Provides increased Shadow Dance CDR and an additional Dance charge. The Shadow Dance uptime is significatnly higher while providing benefits from Soothing Darkness _(Possibly link Soothing Darkness here)_. Is likely a good choice in AoE situations."
- http://prntscr.com/gela1c "allowes" -> "allows"
- http://prntscr.com/gela7b "dont" -> "don't"
- http://prntscr.com/gelafs "strengh of this talent came mainly from" -> "strength of this talent comes mainly from"
- http://prntscr.com/gelaqm "changes to Shadowdance that alowes us to use Shadowdance during the animation" -> "changes to Shadow Dance that allows us to use it during the DfA animation"
- http://prntscr.com/gelb9o "additional dmage to the Evi part" -> "additional damage to the Eviscerate part"
- http://prntscr.com/gelbjj "Shadowdance" -> "Shadow Dance"

**"Equipment" issues** - https://leovdw.github.io/SubtleGuide/guide_equipment.html

- http://prntscr.com/gelovj "source" -> "sources"
- http://prntscr.com/gelp4s "However Legion introduced additional ways to get loot one" -> "However, Legion introduced additional ways to get loot. One"
- http://prntscr.com/gelpvm "is Mythic Plus a scaling dongeon system with reward relative to the difficulty of the dongeon" -> "is Mythic Plus, a scaling dungeon system with rewards relative to the difficulty level of the dungeon."
- http://prntscr.com/gelqe6 "dongeon and the Titanforged system that basicly enables any gear that drops to become alot more powerfull." -> "dungeon. Another source is the War/Titanforged system that enables any gear that drops to become a lot more powerful."
- http://prntscr.com/gelqv0 "lvls" -> "levels"
- http://prntscr.com/gelr5i "If you completed a mythic plus dongeon of the lvl 10 or higher you recive a 930 itemlvl gear piece in the loot chest of your class order hall after the weely reset." -> "If you complete a Mythic Plus dungeon of at least a level 10 or higher, you receive a 935 (or more, depending on Titanforging) item level piece of gear in the weekly loot chest found in your class order hall (resets during weekly reset)."
- http://prntscr.com/gels2u "smal" -> "small"
- http://prntscr.com/gelsbq "Consumables are most of the time one time use effects that dont sustain death with the exception of flasks." -> "Consumables are mostly one-time-use effects that don't persist through death, with the exception of flasks."
- http://prntscr.com/gelsr9 "Gems are procs from the Titanforging system or provided on legendary items in slots without main stat." -> "Gem slots are procs from the Titanforging/Bonus Stat system, or exist naturally on legendary rings/necks, as well as crafted legendaries."
- http://prntscr.com/geltgj "dependent" -> "depending"
- http://prntscr.com/geltpc "Its recommendet to run a simulation to get the most value from Enchants. " -> "It is recommended to run a simulation to determine the best enchants for your gear."
- http://prntscr.com/gelu59 "The same rules that apply to enchants apply to gems. Its recommedet to run a simulation." -> "As with enchants, it is recommended to run a simulation to determine the best gems to use in your gear."
- http://prntscr.com/gelumo "bring itemlvl and one(two " -> "bring item level and one (two "
- http://prntscr.com/geluy5 "artefact" -> "artifact"
- http://prntscr.com/gelv87 "The power lvl of certain traits depend on alot of things including your gear, the bossfight, the NC traits and the strategie. " -> "The power levels of certain traits depends on a lot of things including your gear, the boss, your Netherlight Crucible traits, and your guild's strategy."
- http://prntscr.com/gelvp1 "those" -> "relics"
- http://prntscr.com/gelvvt "Discription" -> "Recommendation"
- http://prntscr.com/gelw5e "One of the strongets ST traits.." -> "One of the strongest pure single-target traits (loses a lot of value as soon as any AoE is introduced to the fight)"
- http://prntscr.com/gelwpa " , also good without on ST fights." -> ", also good without Insignia on single-target fights."
- http://prntscr.com/gelx1u "on ST and MT fights." -> "on single-target and multi-target fights."
- http://prntscr.com/gelxmk _Change all ST/MT instances to single-target/multi-target_
- http://prntscr.com/gelxu2 "One of the weak traits with the changes to  Nightblade, gains abit on value with T19 2P on ST fights." -> "One of the weaker traits with the changes to Nightblade. Gains a bit of value with T19 2P on single-target fights."
- http://prntscr.com/gely8r "Worst dps trait, gets abit stronger if you play  Anticipation." -> "Worst DPS trait. Gets a bit stronger if you select Anticipation."
- http://prntscr.com/gelykv "Is an relic customization introduced in 7.3 that has 3 tiers." -> "The Netherlight Crucible is a relic customization tool introduced in 7.3 that has 3 tiers."
- http://prntscr.com/gelyys "Tier one is always an flat itemlvl increse for your relics up to +15 per " -> "Tier one is always a flat item level increase for your relics, up to +15 per "
- http://prntscr.com/gelzac "The 2nd Tier has 1 out of 6  random light and shadow trait you need to chose between." -> "Tier two has 1 of 6 random light and shadow traits you need to choose between."
- http://prntscr.com/gelznc "between.The 3rd Tier has 3 minor traits that cant be the initial minor trait."   -> "between. Tier three has 3 minor traits that can't be the same as the initial minor trait."
- http://prntscr.com/gem07k "You need to have 60/63/66 in  Concordance of the Legionfall to unlock the Tier 2 Traits and 69/72/75 for Tier 3." -> "You need to have 60/63/66 points in your artifact weapon (8/11/14 points in Concordance of the Legionfall) to unlock the Tier 2 traits, and 69/72/75 points in your artifact weapon to unlock the Tier 3 traits."
- http://prntscr.com/gem0yb "Legendarys" -> "Legendaries"
- http://prntscr.com/gem15s "The strengh of an Legendary Item depends on the gear you have and is relative to the replacements available aswell as the scenario you use them in." -> "The strength of a legendary item depends on your gear, your available replacements for legendaries, as well as the specific situation."
- http://prntscr.com/gem1rr "The assumed best legendary combination can therefore be weaker for your personal situation becouse of relics/replacements. 
Simulations tables can be used to get a basic knowlage of the Legendary's strengh relative to each other. 
The best way to find the Legendary combination suiting for your character is to run a simulation. 
The currently strongest combination for Single target fights is currently  Mantle of the Master Assassin and  The First of the Dead." -> "The so-called "Best in Slot" legendary combination can therefore be weaker for your current situation due to equipped relics and/or your equipped gear.
Simulations can be used to get a basic knowledge of each legendary's strength relative to each other.
The best way to find the best legendary combination is to run a simulation.
That being said, typically the current strongest combination for single-target fights is Mantle of the Master Assassin and The First of the Dead."
- http://prntscr.com/gem32z "Also makes the spec play abit smoother." -> "Also makes the spec play a bit more smoothly."
- http://prntscr.com/gem3fg "Is strong becouse we can line it up with our damage cooldowns." -> "Strong in certain burst AoE situations because we can line it up with our damage-increasing cooldowns."
- http://prntscr.com/gem6zr "Is an underrated Legendary that is strong due to our high initial burst." -> "An underrated legendary that is strong due to our high initial burst."
- http://prntscr.com/gem91n "Every raid tier offers 6 Set pieces that if you wear 2 or 4 of them give you an additional damag boost by enhancing your gameplay in one or another way." -> "Every raid tier offers 6 set pieces that, when you wear 2 or 4 of them, give y ou an additional damage boost by enhancing your gameplay in one way or another."
- http://prntscr.com/gem9lu "legion" -> "Legion"
- http://prntscr.com/gem9u0 "the tier boni without counting in itemlvl" -> "the tier bonuses without counting in item level"
- http://prntscr.com/gema51 "viewer" -> "fewer"
- http://prntscr.com/gemabp "maybe" -> "may"
- http://prntscr.com/gemak6 "has not optimal attributes." -> "has sub-optimal attributes."
- http://prntscr.com/gemax2 "Each Slot offers a diffrent attribut budget therefore some gear slots are stronger then other ones." -> "Each slot offers a different attribute budget which leads to some gear slots being stronger than others."
- http://prntscr.com/gembdk "piece" -> "tier pieces"
- http://prntscr.com/gemblf "secoundary" x2 -> "secondary"
- http://prntscr.com/gembsl "secoundary" x2 -> "secondary"
- http://prntscr.com/gembxm "attribut" -> "attribute"
- http://prntscr.com/gemcdl "With progress in your gear you will more and more aim to gather as mutch of the stronger secoundary attributes as possible while still using high itemlvl pieces due to your main attrubut. " -> "As you gear up, you will start to optimize your gear around your secondary attributes as much as possible while still using as many of your high item level pieces as possible."
- http://prntscr.com/gemdg7 "Certain secoundarie attributes become stronger if you have low amounts of them so the best way to get information about the impact of a certain stat in your current situation is to run a simulation." -> "Certain secondary attributes become stronger if you have low amounts of them. The best way to determine the impact each stat will make based on your current gear is to run a simulation."
- http://prntscr.com/gemdmy "The currently strongest Trinket  is  Specter of Betrayal. Its uses along with diffrent other Trinkets." -> "Currently, the strongest trinket is Specter of Betrayal. It is used alongside various other trinkets."
- http://prntscr.com/geme18 "Convergence of Fates loses on value if you dont use the  Denial of the Half-Giants Legendary and gets usualy replaced with a stonger itemlvl Tomb of Sageras Trinket." -> "Convergence of Fates loses value if you aren't using Denial of the Half-Giants, and as such usually gets replaced with higher item level Tomb of Sargeras trinkets, such as Engine of Eradication" _add item link to Engine_
- http://prntscr.com/gemeth "If we use 2 Trinkets with an on use effect the use of the first one will trigger a 10 secound cooldown for the secound one." -> "If you use 2 trinkets with an on-use effect, the use of one will trigger a 10 second cooldown for the other one."
- http://prntscr.com/gemfb7 "This means that the rotation need to be adjusted if thats the case for you." -> "In this case, the rotation will need to be adjusted to account for the cooldown imposed on the second trinket."
- http://prntscr.com/gemfoe "Ravenhod TC" -> "Ravenholdt TC"
- http://prntscr.com/gemfvn "Intressting Items" -> "Interesting Items"
- http://prntscr.com/gemg56 "aswell" -> "as well"
- http://prntscr.com/gemgbm "pasages" -> "areas"
- http://prntscr.com/gemgjm "member, the chance" -> "member, however the chance"
- http://prntscr.com/geob7r "Increses" -> "Increases"
- http://prntscr.com/geobdd "increses" -> "increases"
- http://prntscr.com/geobkt "progress" -> "progression"
- http://prntscr.com/geobpf "crit, Requires a mouseover macro if you want to dot another" -> "crit, requires a mouseover macro if you want to DoT another"
- http://prntscr.com/gemx8k "Requires you touse the item every 30 secounds to get the most benefits. debuff" -> "Requires you to use the item every 30 seconds to get the greatest benefit. Debuff"
- http://prntscr.com/geocfi " impacts our 3 minute cooldown." -> "impacts our Shadow Blades" _add Shadow Blades link_
- http://prntscr.com/geocsa "consistant" -> "consistent"
- http://prntscr.com/geocxc "relative stationair" -> "relatively stationary"
- http://prntscr.com/geod56 "an" -> "a"
- http://prntscr.com/geodba "alowes" -> "allows"
- http://prntscr.com/geodgi "Makes your carakter imune to knowckbacks during the channel." -> "Makes your character immune to knockbacks during the channel."

**Gameplay - DfA issues** - https://leovdw.github.io/SubtleGuide/guide_dfa.html

- http://prntscr.com/geodzm "specification" -> "specialization"
- http://prntscr.com/geoe6y " up the symbols of death window and align your cooldowns accordingly."   -> "up the Symbols of Death _add link to SoD_ and aligning your cooldowns accordingly."
- http://prntscr.com/geoexk "aswell" -> "as well"
- http://prntscr.com/geof77 "Power1 secound prepull." -> Power with 1 second left on pull timer."
- http://prntscr.com/geofes "Bladeson" -> "Blades on"
- http://prntscr.com/geofl7 "Techniquesprocs" -> "Techniques procs"
- http://prntscr.com/geofqx "Nightbladewill be on 3 CP during the opener, thats fine." -> "Nightblade will be used with 3 CP during the opener which is fine."
- http://prntscr.com/geog1t "off GCD aswell" -> "off the GCD as well"
- http://prntscr.com/geogc0 "Death from Above has different damage parts that trigger at certain points during the animation the main 2 are the initial hit and the Eviscerate part." -> Death from Above has two different damage parts: The initial, AoE hit, and the Eviscerate hit."
- http://prntscr.com/geogpe "intressting" -> "interesting"
- http://prntscr.com/geogux "let" -> "lets"
- http://prntscr.com/geoh07 "specification" -> "specialization"
- http://prntscr.com/geoh4x "dont play the dfa" -> "don't play the DfA"
- http://prntscr.com/geohcx "spamm" -> "spam"
- http://prntscr.com/geohgz "Danceduring" -> "Dance during"
- http://prntscr.com/geohk9 "Aboveanimation." -> "Above animation."
- http://prntscr.com/geohr7 - "Symbols of Deathis usualy not usedduring Death from Abovedue to the base concept of the rotation however its an" -> "Symbols of Death is usually not used during Death from Above due to the base concept of the rotation, however it's an"
- http://prntscr.com/geoi88 " into Shadow Danceafter Death from Aboveyou can" -> "into Shadow Dance after Death from Above, you can"
- http://prntscr.com/geoix8 "can be a result" -> "can be the result"
- http://prntscr.com/geojwj "the Symbols of Deathcooldown And the alignment of Death from Abovewith" -> "the Symbols of Death cooldown and the alignment of Death from Above with"
- http://prntscr.com/geok5a "Deathtogether" -> "Death together"
- http://prntscr.com/geokdh "possile" -> "possible"
- http://prntscr.com/geokjk "mutch on coold down" -> "much on cooldown"
- http://prntscr.com/geokql "Deathyou" -> "Death you"
- http://prntscr.com/geokvw "toprepare" -> "to prepare"
- http://prntscr.com/geol20 "Above, this allowes" -> "Above which allows"
- http://prntscr.com/geol99 "points,pool" -> "points, pool"
- http://prntscr.com/geolda "Deador" -> "Dead or"
- http://prntscr.com/geoljm _add spaces after every spell link_
- http://prntscr.com/geoloi "folowed" -> "followed"
- http://prntscr.com/geolto "builing the" -> "building"
- http://prntscr.com/geolxq _add spaces after every spell link_
- http://prntscr.com/geom33 "folowed" -> "followed"
- http://prntscr.com/geom8k "that you have" -> "that you will have"
- http://prntscr.com/geomek "dont" -> "don't"
- http://prntscr.com/geomir "symbols" -> "Symbols"
- http://prntscr.com/geomlu "secounds." -> "seconds."
- http://prntscr.com/geompo _add spaces after every spell link_
- _tired of linking each paragraph for adding spaces, just go through and add a space after each item link to separate the link from the next word_
- http://prntscr.com/geoq8u "Outide" -> "Outside"
- http://prntscr.com/geoqfh "speced" -> "specced"
- http://prntscr.com/geoqjh "dont" -> "don't"
- http://prntscr.com/geoqvl "secounds" x2 -> "seconds"
- http://prntscr.com/geoqzb "2or" -> "2 or"
- http://prntscr.com/geor69 "lower energy than 50(" -> "less than 50 energy ("
- http://prntscr.com/geored _Seeing reports in Ravenholdt that the Vanish bug has been fixed_
- http://prntscr.com/georma "Multiple target change Use of certain Abilities." -> "Multiple targets changes the use of certain abilities."
- http://prntscr.com/geos22 "Stormif we have 2 or more targets as our combo builder." -> "Storm as our combo point builder if we have 2 or more targets."
- http://prntscr.com/geoscu "applyed" -> "applied"
- http://prntscr.com/geosh3 "at minimum 12 secounds." -> "at least 12 seconds."
- http://prntscr.com/geosn1 "targets result" -> "targets results"
- http://prntscr.com/geost7 "4 or combo" -> "4 or more combo"
- http://prntscr.com/geoswb "targtes" -> "targets"
- http://prntscr.com/geot5q "situations this allowes us to use it more offensively." -> "situations which allows us to use it more often."
- http://prntscr.com/geotdd "Deceitdoesent change the multi taget rotation." -> "Deceit doesn't change the multi-target rotation."
- http://prntscr.com/geotpg "When using multiple Use trinkets the use of one trinket will trigger a 10 sec cooldown on the 2nd one, keep that in mind." -> "When using multiple On-Use trinkets, the use of one trinket will trigger a 10 second cooldown on the second trinket which is something to keep in mind."
- http://prntscr.com/geotz7 "If you use combinations with Specter of Betrayalpriorize it over other trinkets and probably use the 2nd trinket on cd." -> "If you use Specter of Betrayal in combination with another On-Use trinket, prioritize it over your other trinket and most likely use the second trinket on as soon as the cooldown finishes."
- http://prntscr.com/geoubr "Some trinkets have special use conditions i list the popular ones:" -> "Some trinkets have special use conditions, the most popular of which I have listed here:"
- http://prntscr.com/geouk7 "Specter of Betrayal- Use when Shadow Danceduring Symbols of Death. You can macro it to Shadow Danceif you want. Just keep in mind to position propper when using the Trinket." -> "Specter of Betrayal - Use when in Shadow Dance during Symbols of Death. You can macro it to Shadow Dance if you want. Just keep in mind to properly position yourself when using the trinket."
- http://prntscr.com/geov4m "doungeons is common practice, if you" -> "dungeons is common practice. If you"
- http://prntscr.com/geoval "30 secounds cooldown on the new equiped one, you can use this to prepear for specific mob groups/pulls." -> "30 second cooldown on the newly equipped trinket. You can use this time to prepare for specific mob groups/pulls."
- http://prntscr.com/geovkz "dont" -> "don't"
- http://prntscr.com/geovpt "but i dont recommend it becouse of" -> "but I don't recommend it because of"
- http://prntscr.com/geovuu "Enegery Pooling" -> "Energy Pooling"
- http://prntscr.com/geow1u "aswell" -> "as well"
- http://prntscr.com/geow5b "change" -> "chance"
- http://prntscr.com/geowci "Vanishyou want to use it with 55+ energy that condition is usualy met" -> "Vanish - you want to use it with 55+ energy. This condition is usually met"
- http://prntscr.com/geowmh "Shadow Danceyou want to be on a energy level that allowes you to peform 4" -> "Shadow Dance - you want to be at an energy level that allows you to perform 4"
- http://prntscr.com/geowvn "An energy lvl of 70-75 is suefficient for that. I made a calculation about it you" -> "An energy level of 70-75 is sufficient in this situation. I made a calculation about this that you"
- http://prntscr.com/geox89 "into it" -> "into" _this assumes previous issue is accepted/changed_
- http://prntscr.com/geoxer "bossfights" -> "boss fights"
- http://prntscr.com/geoxkt "is only used if you would die else, there should be usualy no" -> "only used if you would otherwise die. There should usually be no"

**Gameplay - non DfA issues** - https://leovdw.github.io/SubtleGuide/guide_non_dfa.html

- http://prntscr.com/geoyln "specification" -> "specialization"
- http://prntscr.com/geoyrl "Power1 secound prepull." -> Power with 1 second left on pull timer."
- http://prntscr.com/geoz46 _rewriting most of this paragraph, the following is my suggestion_ "If you select Marked for Death, you will have an additional ability to use before the pull. This is due to the fact that combo points start decreasing after 20 seconds in an interval of 1 CP every 10 seconds. The changes made the Marked for Death cooldown 40 seconds, so you will always be guaranteed at least 4 combo points at the pull. We always start with Shadowstrike which means we gain an additional cast of Marked for Death during the opener in the best case scenario."
- http://prntscr.com/gep0jj "Nightblade will be on 3 cp during opener when not using  Marked for Death." -> "Nightblade will be used at 3 CP during the opener when not using Marked for Death."
- http://prntscr.com/gep0sg "lose" -> "loss"
- http://prntscr.com/gep0w1 "that" -> "which"
- http://prntscr.com/gep123 "secounds" -> "seconds"
- http://prntscr.com/gep19n "aboth" -> "above"
- http://prntscr.com/gep1nk " Shadow Dance additionaly used when about to cap on " -> "Shadow Dance is also used when you are about to cap on"
- http://prntscr.com/gep1v3 "folowed my" -> "followed by"
- http://prntscr.com/gep22f "is out" -> "is our"
- http://prntscr.com/gep25z "dont" -> "don't"
- http://prntscr.com/gep2d0 "secounds" x2 -> "seconds"
- http://prntscr.com/gep2hj "Eviscerate and  Nightblade are used at 5 or 6 combo points all the time." -> "Eviscerate and Nightblade are always used at 5 or 6 combo points."
- http://prntscr.com/gep2pd "Shuriken Toss is only used when not you need to dump energy and have no other option." -> "Suriken Toss is only used when you are out of range of the boss, need to dump energy, and have no other options."
- http://prntscr.com/gep2yk "applyed" -> "applied"
- http://prntscr.com/gep315 "Boni. Withotu" -> "bonus. Without"
- http://prntscr.com/gep399 "priority" -> "primary"
- http://prntscr.com/gep3f3 "secounds" -> "seconds"
- http://prntscr.com/gep3ho "a priority" -> "primary"
- http://prntscr.com/gep3mm "doesent" -> doesn't"
- http://prntscr.com/geotpg "When using multiple Use trinkets the use of one trinket will trigger a 10 sec cooldown on the 2nd one, keep that in mind." -> "When using multiple On-Use trinkets, the use of one trinket will trigger a 10 second cooldown on the second trinket which is something to keep in mind."
- http://prntscr.com/geotz7 "If you use combinations with Specter of Betrayalpriorize it over other trinkets and probably use the 2nd trinket on cd." -> "If you use Specter of Betrayal in combination with another On-Use trinket, prioritize it over your other trinket and most likely use the second trinket on as soon as the cooldown finishes."
- http://prntscr.com/geoubr "Some trinkets have special use conditions i list the popular ones:" -> "Some trinkets have special use conditions, the most popular of which I have listed here:"
- http://prntscr.com/geouk7 "Specter of Betrayal- Use when Shadow Danceduring Symbols of Death. You can macro it to Shadow Danceif you want. Just keep in mind to position propper when using the Trinket." -> "Specter of Betrayal - Use when in Shadow Dance during Symbols of Death. You can macro it to Shadow Dance if you want. Just keep in mind to properly position yourself when using the trinket."
- http://prntscr.com/geov4m "doungeons is common practice, if you" -> "dungeons is common practice. If you"
- http://prntscr.com/geoval "30 secounds cooldown on the new equiped one, you can use this to prepear for specific mob groups/pulls." -> "30 second cooldown on the newly equipped trinket. You can use this time to prepare for specific mob groups/pulls."
- http://prntscr.com/geovuu "Enegery Pooling" -> "Energy Pooling"
- http://prntscr.com/geow1u "aswell" -> "as well"
- http://prntscr.com/geow5b "change" -> "chance"
- http://prntscr.com/geowmh "Shadow Danceyou want to be on a energy level that allowes you to peform 4" -> "Shadow Dance - you want to be at an energy level that allows you to perform 4"
- http://prntscr.com/geowvn "An energy lvl of 70-75 is suefficient for that. I made a calculation about it you" -> "An energy level of 70-75 is sufficient in this situation. I made a calculation about this that you"
- http://prntscr.com/geox89 "into it" -> "into" _this assumes previous issue is accepted/changed_
- http://prntscr.com/geoxer "bossfights" -> "boss fights"
- http://prntscr.com/geoxkt "is only used if you would die else, there should be usualy no" -> "only used if you would otherwise die. There should usually be no"

Enjoy your massive amount of work I gave you, and good job on the guide. AM that kind of orc, out.

**Comment by leovdw** [comment]
My god you're not messing around, thx alot for the feedback, will correct that when I get to argus :P

**Comment by fuu1** [comment]
thanks for the time/effort, all changes should be in.
